{"errorMessage": "An error occurred (ResourceNotFoundException) when calling the PutRecord operation: Stream lowd under account 990386817329 not found.", "errorType": "ResourceNotFoundException", "requestId": "5ba50a54-dbbf-4e9e-b2fc-2652fee5dc6b", "stackTrace": ["  File \"/var/task/app.py\", line 30, in lambda_handler\n    put_record(counter)\n", "  File \"/var/task/app.py\", line 14, in put_record\n    response = kinesis_client.put_record(\n", "  File \"/var/runtime/botocore/client.py\", line 553, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 1009, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}